title: GROOVE - A tool for graph transformation and verification
description: GROOVE home page
plugins:
  - jekyll-relative-links
theme: documentation-theme-jekyll
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - DEVELOPERS.md
