title: GROOVE - A tool for graph transformation and state space exploration
description: Tool home page
plugins:
  - jekyll-relative-links
theme: jekyll-theme-minimal
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
